Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.synced_folder ".", "{{ cookiecutter.snc_dr }}"
    config.vm.provision :shell, path: "provision.sh"
    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.vm.network :forwarded_port, guest: 8000, host: 8000

    config.vm.provider :virtualbox do |v|
      v.customize [ "modifyvm", :id, "--cpus", {{ cookiecutter.CPUS }} ]
      v.customize [ "modifyvm", :id, "--memory", {{ cookiecutter.RAM }} ]
      v.customize [ "modifyvm", :id, "--name", "{{ cookiecutter.project_name }}" ]
    end
end
